name: Update profile metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: profile-metrics
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6
        with:
          filename: profile/github.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header, activity, repositories
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_threshold: 0.5%
          plugin_languages_other: yes
          plugin_languages_skipped: mcthesw/mcthesw.github.io
          config_timezone: Asia/Shanghai
          output_condition: data-changed
          plugins_errors_fatal: yes
          verify: yes

      - name: Generate Steam activity
        uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6
        with:
          filename: profile/steam.svg
          token: NOT_NEEDED
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198288679129"
          plugin_steam_sections: recently-played
          plugin_steam_recent_games_limit: 2
          plugin_steam_achievements_limit: 0
          config_timezone: Asia/Shanghai
          output_condition: data-changed
          plugins_errors_fatal: yes
          verify: yes
